networks:
  - id: 10143
    rpc_config:
      url: https://testnet-rpc.monad.xyz  # Replace with actual RPC URL
contracts:
  - name: Magma
    address: 0x2c9C959516e9AAEdB2C748224a41249202ca8BE7
    abi_path: ./abis/Magma.json
    handlers:
      - event: "*"
        handler: handleAllEvents
  - name: Monad2048
    address: 0xe0FA8195AE92b9C473c0c0c12c2D6bCbd245De47
    abi_path: ./abis/Monad2048.json
    handlers:
      - event: "*"
        handler: handleAllEvents
  - name: WrappedMonad
    address: 0x760AfE86e5de5fa0Ee542fc7B7B713e1c5425701
    abi_path: ./abis/WrappedMonad.json
    handlers:
      - event: "*"
        handler: handleAllEvents
  - name: Ambient
    address: 0x88B96aF200c8a9c35442C8AC6cd3D22695AaE4F0
    abi_path: ./abis/Ambient.json
    handlers:
      - event: "*"
        handler: handleAllEvents
  - name: Madness
    address: 0x64Aff7245EbdAAECAf266852139c67E4D8DBa4de
    abi_path: ./abis/Madness.json
    handlers:
      - event: "*"
        handler: handleAllEvents